Feat: add ReduceLROnPlateau support
dreamquark-ai/tabnet pull request #182
Opened 2020-09-09 09:57 UTC by bennyjg

Enable use of lr_scheduler.ReduceLROnPlateau which requires a loss parameter during the step phase.
Change suggested - move scheduler.step() to outer training loop and add stopping_loss as parameter for case of ReduceLROnPlateau scheduler.

**What kind of change does this PR introduce?**
Enhancement

**Does this PR introduce a breaking change?**
Not to my best knowledge

**What needs to be documented once your changes are merged?**
indicate support for this scheduler in the documentation. This LR_scheduler can be very useful.

**Closing issues**
Closes #160

2020-09-09 20:53 UTC, eduardocarvp requested changes
Thanks, @bennyjg !
I see no problem removing the scheduler step from `train_epoch` function and adding it to the main loop if the loss is needed. However, I guess you should remove the same scheduler lines below from the `TabNetRegressor` class as well:
```
if self.scheduler is not None:
    self.scheduler.step()
```

2020-09-10 06:18 UTC, bennyjg commented
True, I missed that part.
Should I add it as another commit?
Benny

> On 9 Sep 2020, at 23:53, Eduardo Carvalho <notifications@github.com> wrote:
> 
> ﻿
> @eduardocarvp requested changes on this pull request.
> 
> Thanks, @bennyjg !
> I see no problem removing the scheduler step from train_epoch function and adding it to the main loop if the loss is needed. However, I guess you should remove the same scheduler lines below from the TabNetRegressor class as well:
> 
> if self.scheduler is not None:
>     self.scheduler.step()
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-10 06:27 UTC, bennyjg commented
> Thanks, @bennyjg !
> I see no problem removing the scheduler step from `train_epoch` function and adding it to the main loop if the loss is needed. However, I guess you should remove the same scheduler lines below from the `TabNetRegressor` class as well:
> 
> ```
> if self.scheduler is not None:
>     self.scheduler.step()
> ```

Hi @eduardocarvp , I made the additional change you suggested. Thanks!
I hope it is now ready to be merged. :)

2020-09-11 11:23 UTC, Optimox commented
@bennyjg I think we are almost good! Any chance you could squash your last commit to have only one commit for this PR?

2020-09-11 11:26 UTC, bennyjg commented
> @bennyjg I think we are almost good! Any chance you could squash your last commit to have only one commit for this PR?

Is there a Git trick to do that without resubmitting the whole CR from scratch?
Like a merge button of some sort??

2020-09-11 13:07 UTC, eduardocarvp commented
@bennyjg, sure! You can use `git rebase -i HEAD~2` and then squash the second commit. Remember to `push --force-with-lease` after you're done.

Some doc here if you don't know `git rebase -i`:  https://opensource.com/article/20/4/git-rebase-i

2020-09-11 21:10 UTC, Optimox commented
Well this will cost me some conflicts with my PR #184 but you were first! Thank you very much for contributing to pytorch-tabnet, your help is much appreciated!

2020-09-11 21:12 UTC, Optimox approved these changes
Thanks approved!

2020-09-11 21:14 UTC, merged

2020-09-12 01:39 UTC, bennyjg commented
Thanks! Enjoyed it :)
Hope to see more exciting features added. 

> On 12 Sep 2020, at 0:10, Optimox <notifications@github.com> wrote:
> 
> ﻿
> Well this will cost me some conflicts with my PR #184 but you were first! Thank you very much for contributing to pytorch-tabnet, your help is much appreciated!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.